# configuration file for MX PROJECT anticheat

IKnowWhatImDo: true

# checks

#COMBAT
KillauraForced:
  enable: true
  vl: 30
  vlfader: 2

KillauraVM:
  enable: true
  #pitch based
  default:
    enable: true
    vl: 10
    vlfader: 3
    vlstop: 30
    brutality: 3.75
    displacement factor: 5
    center offset: 0
    point express: 4
    air express offset: 9.25
    balancer:
      # balancer
      # 1 2 3 | 4 5 6 7 | 8 9
      # 1 2 3 - decreace to multi (+ bigger VL)
      # 8 9 - increace to multi (- smaller VL)
      enabled: true
      increace: 1.0 # value like "8 9"
      increace_multi: 2 #balancer +
      decreace: 2.0 # value like "1 2 3"
      decreace_multi: 2.5 #balancer -
      #balancer created for advanced flags

  #yaw based
  point:
    enable: true
    vl: 3
    vlfader: 8
    vlstop: 60
    brutality: 1.25
    displacement factor: 10
    center offset: 0
    balancer:
      # balancer
      # 1 2 3 | 4 5 6 7 | 8 9
      # 1 2 3 - decreace to multi (+ bigger VL)
      # 8 9 - increace to multi (- smaller VL)
      enabled: true
      increace: 2.0 # value like "8 9"
      increace_multi: 3 #balancer +
      decreace: 1.25 # value like "1 2 3"
      decreace_multi: 1.5 #balancer -
      #balancer created for advanced flags

#MOVEMENT
Move:
  A:
    enable: true
    vl: 5
    vlstop: 0
    vlfader: 5
  B:
    enable: true
    vl: 5
    vlstop: 35
    vlfader: 5
  C:
    enable: true
    vl: 20
    vlstop: 13
    vlfader: 5
    flag after count of packets: 3
MachineLearning:
  JumpSpeed:
    enable: true
    #global vl
    vl: 100
    vlstop: 15
    vlfader: 5
    # local vl
    localvl: 15
    localvlstop: 40
    localvlfader: 3
    #advanced support (ping / lags protection)
    #but it cause the weakest blatant checks
    # (recommend)
    advanced_support: true

# vl manager
# %player% - player placeholder
# %reason% - reason placeholder

PunishCommand: "kick %player% %reason%"
PunishVL: 75